{% set name = "zziplib" %}
{% set version = "0.13.75" %}
{% set sha256 = "1c167ab4cec1842d5b25bae1a9ce02ed671f23bc614c6c32edbe6d715097e65e" %}
package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/gdraheim/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: {{ sha256 }}
    patches:
      # python 2 only for docs building
      - remove_docs_from_build.patch
  - path: CMakeLists.txt  # [win]

build:
  number: 1
  skip: true  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - pkg-config
    - autoconf  # [not win]
    - cmake  # [win]
    - python
    - make
  host:
    - zlib


test:
  commands:
    - test -f $PREFIX/lib/libzzip${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/include/zzip.h  # [unix]
    - if NOT exist %LIBRARY_LIB%/zziplib.lib exit 1  # [win]
    - if NOT exist %LIBRARY_BIN%/zziplib.dll exit 1  # [win]
    - if NOT exist %LIBRARY_INC%/zzip/zzip.h exit 1  # [win]


about:
  home: http://zziplib.sourceforge.net/
  summary: The zziplib library is intentionally lightweight, it offers the ability to easily extract data from files archived in a single zip file.
  # See https://github.com/gdraheim/zziplib/blob/v0.13.69/README#L13-L18
  license: LGPL-2.0-or-later.html OR MPL-1.1
  license_file:
    - docs/COPYING.LIB
    - docs/COPYING.MPL
    - docs/copying.htm

extra:
  recipe-maintainers:
    - wolfv
    - lesteve
    - traversaro
